// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/merchant/merchant.proto

package merchant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Merchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ContactInfo   string                 `protobuf:"bytes,3,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	OwnerUserId   int64                  `protobuf:"varint,5,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Merchant) Reset() {
	*x = Merchant{}
	mi := &file_api_merchant_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Merchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merchant) ProtoMessage() {}

func (x *Merchant) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merchant.ProtoReflect.Descriptor instead.
func (*Merchant) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *Merchant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Merchant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Merchant) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

func (x *Merchant) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Merchant) GetOwnerUserId() int64 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

type CreateMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContactInfo   string                 `protobuf:"bytes,2,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	OwnerUserId   int64                  `protobuf:"varint,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantRequest) Reset() {
	*x = CreateMerchantRequest{}
	mi := &file_api_merchant_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantRequest) ProtoMessage() {}

func (x *CreateMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantRequest) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMerchantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMerchantRequest) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

func (x *CreateMerchantRequest) GetOwnerUserId() int64 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

type CreateMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *Merchant              `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantResponse) Reset() {
	*x = CreateMerchantResponse{}
	mi := &file_api_merchant_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantResponse) ProtoMessage() {}

func (x *CreateMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantResponse.ProtoReflect.Descriptor instead.
func (*CreateMerchantResponse) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMerchantResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type GetMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantRequest) Reset() {
	*x = GetMerchantRequest{}
	mi := &file_api_merchant_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantRequest) ProtoMessage() {}

func (x *GetMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantRequest) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{3}
}

func (x *GetMerchantRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *Merchant              `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantResponse) Reset() {
	*x = GetMerchantResponse{}
	mi := &file_api_merchant_merchant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantResponse) ProtoMessage() {}

func (x *GetMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantResponse) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{4}
}

func (x *GetMerchantResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type ListMerchantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsRequest) Reset() {
	*x = ListMerchantsRequest{}
	mi := &file_api_merchant_merchant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsRequest) ProtoMessage() {}

func (x *ListMerchantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsRequest.ProtoReflect.Descriptor instead.
func (*ListMerchantsRequest) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{5}
}

func (x *ListMerchantsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMerchantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMerchantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchants     []*Merchant            `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsResponse) Reset() {
	*x = ListMerchantsResponse{}
	mi := &file_api_merchant_merchant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsResponse) ProtoMessage() {}

func (x *ListMerchantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsResponse.ProtoReflect.Descriptor instead.
func (*ListMerchantsResponse) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{6}
}

func (x *ListMerchantsResponse) GetMerchants() []*Merchant {
	if x != nil {
		return x.Merchants
	}
	return nil
}

func (x *ListMerchantsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AddProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int64                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceCents    int64                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ActorUserId   int64                  `protobuf:"varint,8,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	mi := &file_api_merchant_merchant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{7}
}

func (x *AddProductRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *AddProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddProductRequest) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *AddProductRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AddProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AddProductRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *AddProductRequest) GetActorUserId() int64 {
	if x != nil {
		return x.ActorUserId
	}
	return 0
}

type AddProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductResponse) Reset() {
	*x = AddProductResponse{}
	mi := &file_api_merchant_merchant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductResponse) ProtoMessage() {}

func (x *AddProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductResponse.ProtoReflect.Descriptor instead.
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{8}
}

func (x *AddProductResponse) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int64                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ActorUserId   int64                  `protobuf:"varint,3,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_api_merchant_merchant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProductRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *DeleteProductRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeleteProductRequest) GetActorUserId() int64 {
	if x != nil {
		return x.ActorUserId
	}
	return 0
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_api_merchant_merchant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CurrentMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   int64                  `protobuf:"varint,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	MerchantId    *int64                 `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3,oneof" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentMerchantRequest) Reset() {
	*x = CurrentMerchantRequest{}
	mi := &file_api_merchant_merchant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentMerchantRequest) ProtoMessage() {}

func (x *CurrentMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentMerchantRequest.ProtoReflect.Descriptor instead.
func (*CurrentMerchantRequest) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{11}
}

func (x *CurrentMerchantRequest) GetActorUserId() int64 {
	if x != nil {
		return x.ActorUserId
	}
	return 0
}

func (x *CurrentMerchantRequest) GetMerchantId() int64 {
	if x != nil && x.MerchantId != nil {
		return *x.MerchantId
	}
	return 0
}

type CurrentMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *Merchant              `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentMerchantResponse) Reset() {
	*x = CurrentMerchantResponse{}
	mi := &file_api_merchant_merchant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentMerchantResponse) ProtoMessage() {}

func (x *CurrentMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentMerchantResponse.ProtoReflect.Descriptor instead.
func (*CurrentMerchantResponse) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{12}
}

func (x *CurrentMerchantResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type MerchantProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceCents    int64                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	MerchantId    int64                  `protobuf:"varint,8,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantProduct) Reset() {
	*x = MerchantProduct{}
	mi := &file_api_merchant_merchant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantProduct) ProtoMessage() {}

func (x *MerchantProduct) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantProduct.ProtoReflect.Descriptor instead.
func (*MerchantProduct) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{13}
}

func (x *MerchantProduct) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MerchantProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MerchantProduct) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MerchantProduct) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *MerchantProduct) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *MerchantProduct) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MerchantProduct) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *MerchantProduct) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type ListMerchantProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   int64                  `protobuf:"varint,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	MerchantId    *int64                 `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3,oneof" json:"merchant_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantProductsRequest) Reset() {
	*x = ListMerchantProductsRequest{}
	mi := &file_api_merchant_merchant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantProductsRequest) ProtoMessage() {}

func (x *ListMerchantProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantProductsRequest.ProtoReflect.Descriptor instead.
func (*ListMerchantProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{14}
}

func (x *ListMerchantProductsRequest) GetActorUserId() int64 {
	if x != nil {
		return x.ActorUserId
	}
	return 0
}

func (x *ListMerchantProductsRequest) GetMerchantId() int64 {
	if x != nil && x.MerchantId != nil {
		return *x.MerchantId
	}
	return 0
}

func (x *ListMerchantProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMerchantProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMerchantProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*MerchantProduct     `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantProductsResponse) Reset() {
	*x = ListMerchantProductsResponse{}
	mi := &file_api_merchant_merchant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantProductsResponse) ProtoMessage() {}

func (x *ListMerchantProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantProductsResponse.ProtoReflect.Descriptor instead.
func (*ListMerchantProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{15}
}

func (x *ListMerchantProductsResponse) GetProducts() []*MerchantProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListMerchantProductsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateMerchantProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ActorUserId   int64                  `protobuf:"varint,2,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	MerchantId    *int64                 `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3,oneof" json:"merchant_id,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	PriceCents    *int64                 `protobuf:"varint,6,opt,name=price_cents,json=priceCents,proto3,oneof" json:"price_cents,omitempty"`
	Stock         *int32                 `protobuf:"varint,7,opt,name=stock,proto3,oneof" json:"stock,omitempty"`
	Category      *string                `protobuf:"bytes,8,opt,name=category,proto3,oneof" json:"category,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantProductRequest) Reset() {
	*x = UpdateMerchantProductRequest{}
	mi := &file_api_merchant_merchant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantProductRequest) ProtoMessage() {}

func (x *UpdateMerchantProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantProductRequest) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateMerchantProductRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateMerchantProductRequest) GetActorUserId() int64 {
	if x != nil {
		return x.ActorUserId
	}
	return 0
}

func (x *UpdateMerchantProductRequest) GetMerchantId() int64 {
	if x != nil && x.MerchantId != nil {
		return *x.MerchantId
	}
	return 0
}

func (x *UpdateMerchantProductRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateMerchantProductRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateMerchantProductRequest) GetPriceCents() int64 {
	if x != nil && x.PriceCents != nil {
		return *x.PriceCents
	}
	return 0
}

func (x *UpdateMerchantProductRequest) GetStock() int32 {
	if x != nil && x.Stock != nil {
		return *x.Stock
	}
	return 0
}

func (x *UpdateMerchantProductRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *UpdateMerchantProductRequest) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

type UpdateMerchantProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *MerchantProduct       `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantProductResponse) Reset() {
	*x = UpdateMerchantProductResponse{}
	mi := &file_api_merchant_merchant_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantProductResponse) ProtoMessage() {}

func (x *UpdateMerchantProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_merchant_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateMerchantProductResponse) Descriptor() ([]byte, []int) {
	return file_api_merchant_merchant_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateMerchantProductResponse) GetProduct() *MerchantProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_api_merchant_merchant_proto protoreflect.FileDescriptor

const file_api_merchant_merchant_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/merchant/merchant.proto\x12\bmerchant\"\x94\x01\n" +
	"\bMerchant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcontact_info\x18\x03 \x01(\tR\vcontactInfo\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\"\n" +
	"\rowner_user_id\x18\x05 \x01(\x03R\vownerUserId\"r\n" +
	"\x15CreateMerchantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fcontact_info\x18\x02 \x01(\tR\vcontactInfo\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\x03R\vownerUserId\"H\n" +
	"\x16CreateMerchantResponse\x12.\n" +
	"\bmerchant\x18\x01 \x01(\v2\x12.merchant.MerchantR\bmerchant\"$\n" +
	"\x12GetMerchantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"E\n" +
	"\x13GetMerchantResponse\x12.\n" +
	"\bmerchant\x18\x01 \x01(\v2\x12.merchant.MerchantR\bmerchant\"G\n" +
	"\x14ListMerchantsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"_\n" +
	"\x15ListMerchantsResponse\x120\n" +
	"\tmerchants\x18\x01 \x03(\v2\x12.merchant.MerchantR\tmerchants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xfe\x01\n" +
	"\x11AddProductRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x03R\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x03R\n" +
	"priceCents\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12\"\n" +
	"\ractor_user_id\x18\b \x01(\x03R\vactorUserId\"3\n" +
	"\x12AddProductResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"z\n" +
	"\x14DeleteProductRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x03R\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\"\n" +
	"\ractor_user_id\x18\x03 \x01(\x03R\vactorUserId\"1\n" +
	"\x15DeleteProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"r\n" +
	"\x16CurrentMerchantRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\x03R\vactorUserId\x12$\n" +
	"\vmerchant_id\x18\x02 \x01(\x03H\x00R\n" +
	"merchantId\x88\x01\x01B\x0e\n" +
	"\f_merchant_id\"I\n" +
	"\x17CurrentMerchantResponse\x12.\n" +
	"\bmerchant\x18\x01 \x01(\v2\x12.merchant.MerchantR\bmerchant\"\xe8\x01\n" +
	"\x0fMerchantProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x03R\n" +
	"priceCents\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vmerchant_id\x18\b \x01(\x03R\n" +
	"merchantId\"\xa8\x01\n" +
	"\x1bListMerchantProductsRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\x03R\vactorUserId\x12$\n" +
	"\vmerchant_id\x18\x02 \x01(\x03H\x00R\n" +
	"merchantId\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSizeB\x0e\n" +
	"\f_merchant_id\"k\n" +
	"\x1cListMerchantProductsResponse\x125\n" +
	"\bproducts\x18\x01 \x03(\v2\x19.merchant.MerchantProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa9\x03\n" +
	"\x1cUpdateMerchantProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\"\n" +
	"\ractor_user_id\x18\x02 \x01(\x03R\vactorUserId\x12$\n" +
	"\vmerchant_id\x18\x03 \x01(\x03H\x00R\n" +
	"merchantId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x01R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x02R\vdescription\x88\x01\x01\x12$\n" +
	"\vprice_cents\x18\x06 \x01(\x03H\x03R\n" +
	"priceCents\x88\x01\x01\x12\x19\n" +
	"\x05stock\x18\a \x01(\x05H\x04R\x05stock\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\b \x01(\tH\x05R\bcategory\x88\x01\x01\x12 \n" +
	"\timage_url\x18\t \x01(\tH\x06R\bimageUrl\x88\x01\x01B\x0e\n" +
	"\f_merchant_idB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_price_centsB\b\n" +
	"\x06_stockB\v\n" +
	"\t_categoryB\f\n" +
	"\n" +
	"_image_url\"T\n" +
	"\x1dUpdateMerchantProductResponse\x123\n" +
	"\aproduct\x18\x01 \x01(\v2\x19.merchant.MerchantProductR\aproduct2\xcb\x05\n" +
	"\x0fMerchantService\x12S\n" +
	"\x0eCreateMerchant\x12\x1f.merchant.CreateMerchantRequest\x1a .merchant.CreateMerchantResponse\x12J\n" +
	"\vGetMerchant\x12\x1c.merchant.GetMerchantRequest\x1a\x1d.merchant.GetMerchantResponse\x12P\n" +
	"\rListMerchants\x12\x1e.merchant.ListMerchantsRequest\x1a\x1f.merchant.ListMerchantsResponse\x12G\n" +
	"\n" +
	"AddProduct\x12\x1b.merchant.AddProductRequest\x1a\x1c.merchant.AddProductResponse\x12P\n" +
	"\rDeleteProduct\x12\x1e.merchant.DeleteProductRequest\x1a\x1f.merchant.DeleteProductResponse\x12Y\n" +
	"\x12GetCurrentMerchant\x12 .merchant.CurrentMerchantRequest\x1a!.merchant.CurrentMerchantResponse\x12e\n" +
	"\x14ListMerchantProducts\x12%.merchant.ListMerchantProductsRequest\x1a&.merchant.ListMerchantProductsResponse\x12h\n" +
	"\x15UpdateMerchantProduct\x12&.merchant.UpdateMerchantProductRequest\x1a'.merchant.UpdateMerchantProductResponseB\x1aZ\x18go-commerce/api/merchantb\x06proto3"

var (
	file_api_merchant_merchant_proto_rawDescOnce sync.Once
	file_api_merchant_merchant_proto_rawDescData []byte
)

func file_api_merchant_merchant_proto_rawDescGZIP() []byte {
	file_api_merchant_merchant_proto_rawDescOnce.Do(func() {
		file_api_merchant_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_merchant_merchant_proto_rawDesc), len(file_api_merchant_merchant_proto_rawDesc)))
	})
	return file_api_merchant_merchant_proto_rawDescData
}

var file_api_merchant_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_merchant_merchant_proto_goTypes = []any{
	(*Merchant)(nil),                      // 0: merchant.Merchant
	(*CreateMerchantRequest)(nil),         // 1: merchant.CreateMerchantRequest
	(*CreateMerchantResponse)(nil),        // 2: merchant.CreateMerchantResponse
	(*GetMerchantRequest)(nil),            // 3: merchant.GetMerchantRequest
	(*GetMerchantResponse)(nil),           // 4: merchant.GetMerchantResponse
	(*ListMerchantsRequest)(nil),          // 5: merchant.ListMerchantsRequest
	(*ListMerchantsResponse)(nil),         // 6: merchant.ListMerchantsResponse
	(*AddProductRequest)(nil),             // 7: merchant.AddProductRequest
	(*AddProductResponse)(nil),            // 8: merchant.AddProductResponse
	(*DeleteProductRequest)(nil),          // 9: merchant.DeleteProductRequest
	(*DeleteProductResponse)(nil),         // 10: merchant.DeleteProductResponse
	(*CurrentMerchantRequest)(nil),        // 11: merchant.CurrentMerchantRequest
	(*CurrentMerchantResponse)(nil),       // 12: merchant.CurrentMerchantResponse
	(*MerchantProduct)(nil),               // 13: merchant.MerchantProduct
	(*ListMerchantProductsRequest)(nil),   // 14: merchant.ListMerchantProductsRequest
	(*ListMerchantProductsResponse)(nil),  // 15: merchant.ListMerchantProductsResponse
	(*UpdateMerchantProductRequest)(nil),  // 16: merchant.UpdateMerchantProductRequest
	(*UpdateMerchantProductResponse)(nil), // 17: merchant.UpdateMerchantProductResponse
}
var file_api_merchant_merchant_proto_depIdxs = []int32{
	0,  // 0: merchant.CreateMerchantResponse.merchant:type_name -> merchant.Merchant
	0,  // 1: merchant.GetMerchantResponse.merchant:type_name -> merchant.Merchant
	0,  // 2: merchant.ListMerchantsResponse.merchants:type_name -> merchant.Merchant
	0,  // 3: merchant.CurrentMerchantResponse.merchant:type_name -> merchant.Merchant
	13, // 4: merchant.ListMerchantProductsResponse.products:type_name -> merchant.MerchantProduct
	13, // 5: merchant.UpdateMerchantProductResponse.product:type_name -> merchant.MerchantProduct
	1,  // 6: merchant.MerchantService.CreateMerchant:input_type -> merchant.CreateMerchantRequest
	3,  // 7: merchant.MerchantService.GetMerchant:input_type -> merchant.GetMerchantRequest
	5,  // 8: merchant.MerchantService.ListMerchants:input_type -> merchant.ListMerchantsRequest
	7,  // 9: merchant.MerchantService.AddProduct:input_type -> merchant.AddProductRequest
	9,  // 10: merchant.MerchantService.DeleteProduct:input_type -> merchant.DeleteProductRequest
	11, // 11: merchant.MerchantService.GetCurrentMerchant:input_type -> merchant.CurrentMerchantRequest
	14, // 12: merchant.MerchantService.ListMerchantProducts:input_type -> merchant.ListMerchantProductsRequest
	16, // 13: merchant.MerchantService.UpdateMerchantProduct:input_type -> merchant.UpdateMerchantProductRequest
	2,  // 14: merchant.MerchantService.CreateMerchant:output_type -> merchant.CreateMerchantResponse
	4,  // 15: merchant.MerchantService.GetMerchant:output_type -> merchant.GetMerchantResponse
	6,  // 16: merchant.MerchantService.ListMerchants:output_type -> merchant.ListMerchantsResponse
	8,  // 17: merchant.MerchantService.AddProduct:output_type -> merchant.AddProductResponse
	10, // 18: merchant.MerchantService.DeleteProduct:output_type -> merchant.DeleteProductResponse
	12, // 19: merchant.MerchantService.GetCurrentMerchant:output_type -> merchant.CurrentMerchantResponse
	15, // 20: merchant.MerchantService.ListMerchantProducts:output_type -> merchant.ListMerchantProductsResponse
	17, // 21: merchant.MerchantService.UpdateMerchantProduct:output_type -> merchant.UpdateMerchantProductResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_merchant_merchant_proto_init() }
func file_api_merchant_merchant_proto_init() {
	if File_api_merchant_merchant_proto != nil {
		return
	}
	file_api_merchant_merchant_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_merchant_merchant_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_merchant_merchant_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_merchant_merchant_proto_rawDesc), len(file_api_merchant_merchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_merchant_merchant_proto_goTypes,
		DependencyIndexes: file_api_merchant_merchant_proto_depIdxs,
		MessageInfos:      file_api_merchant_merchant_proto_msgTypes,
	}.Build()
	File_api_merchant_merchant_proto = out.File
	file_api_merchant_merchant_proto_goTypes = nil
	file_api_merchant_merchant_proto_depIdxs = nil
}
